import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  variable: "--font-ibm-plex-sans-thai",
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${ibmPlexSansThai.variable} antialiased`}
      >
        <Toaster position="top-center" toastOptions={{
          classNames: {
            success: '!bg-green-500 !text-white !border-none',
            error: '!bg-red-400 !text-white !border-none',
            warning: '!bg-yellow-500 !text-white !border-none',

            description: '!text-white/90',
            actionButton: '!bg-white !text-black',
            cancelButton: '!bg-white/20 !text-white',
          },
        }} />

        {children}
      </body>
    </html>
  );
}
